import os

SRC_DIR = r"d:\agentic-solution-domain-insurance\src\source_intelligence"
os.makedirs(SRC_DIR, exist_ok=True)

# types.py
with open(os.path.join(SRC_DIR, "types.py"), "w", encoding="utf-8") as f:
    f.write('"""Type compatibility rules for semantic concepts."""\n\n')
    f.write('TYPE_EXPECTATIONS = {\n')
    f.write('    "DateType": ["date", "effective_date", "expiration_date", "loss_date", "birth_date"],\n')
    f.write('    "TimestampType": ["source_updated_ts", "created_at", "updated_at"],\n')
    f.write('    "StringType": ["policy_id", "policy_number", "policy_status", "claim_id", "claim_status", "party_id", "party_type", "product_code", "display_name", "contact_channel"],\n')
    f.write('    "DecimalType": ["claimed_amount", "premium_amount", "deductible_amount"],\n')
    f.write('    "IntegerType": ["count", "sequence", "version"],\n')
    f.write('    "BooleanType": ["is_active", "is_deleted", "flag"],\n')
    f.write('}\n\n\n')
    f.write('def check_type_compatibility(physical_type: str, column_name: str) -> float:\n')
    f.write('    """Check if physical type is compatible with column name semantics.\n')
    f.write('    Returns type_strength (0.0 to 1.0).\n')
    f.write('    """\n')
    f.write('    type_str = str(physical_type)\n')
    f.write('    name = column_name.lower()\n')
    f.write('    for expected_type, keywords in TYPE_EXPECTATIONS.items():\n')
    f.write('        if expected_type in type_str:\n')
    f.write('            if any(kw in name for kw in keywords):\n')
    f.write('                return 0.8\n')
    f.write('            return 0.5\n')
    f.write('    return 0.4\n')
print("Created: types.py")

# privacy.py
with open(os.path.join(SRC_DIR, "privacy.py"), "w", encoding="utf-8") as f:
    f.write('"""Privacy classification rules."""\n')
    f.write('from .naming import detect_personal_data\n\n\n')
    f.write('def classify_privacy(column_name: str) -> tuple:\n')
    f.write('    """Classify column privacy based on name patterns.\n')
    f.write('    Returns (privacy_class, rationale).\n')
    f.write('    """\n')
    f.write('    if detect_personal_data(column_name):\n')
    f.write('        return "PERSONAL_DATA", "Column name matches personal-data rule; privacy review required"\n')
    f.write('    return "INTERNAL", "Technical or business metadata; no direct PII detected by MVP rule"\n')
print("Created: privacy.py")

# relationships.py
with open(os.path.join(SRC_DIR, "relationships.py"), "w", encoding="utf-8") as f:
    f.write('"""Relationship inference from key naming and type patterns."""\n\n')
    f.write('PRIMARY_KEYS = {\n')
    f.write('    "bronze_policy": "policy_id",\n')
    f.write('    "bronze_policyholder": "party_id",\n')
    f.write('    "bronze_claim": "claim_id",\n')
    f.write('}\n\n')
    f.write('KNOWN_RELATIONSHIPS = {\n')
    f.write('    ("bronze_claim", "policy_id"): ("bronze_policy", "policy_id"),\n')
    f.write('    ("bronze_policy", "insured_party_id"): ("bronze_policyholder", "party_id"),\n')
    f.write('}\n\n\n')
    f.write('def infer_key_role(table_name: str, column_name: str) -> str:\n')
    f.write('    """Infer the key role of a column."""\n')
    f.write('    if PRIMARY_KEYS.get(table_name) == column_name:\n')
    f.write('        return "PRIMARY_KEY_CANDIDATE"\n')
    f.write('    if column_name.endswith("_id"):\n')
    f.write('        return "FOREIGN_KEY_CANDIDATE"\n')
    f.write('    return "NON_KEY"\n\n\n')
    f.write('def infer_relationship(table_name: str, column_name: str):\n')
    f.write('    """Infer relationship evidence for a column."""\n')
    f.write('    key = (table_name, column_name)\n')
    f.write('    if key in KNOWN_RELATIONSHIPS:\n')
    f.write('        target_table, target_column = KNOWN_RELATIONSHIPS[key]\n')
    f.write('        return f"Inferred relationship: {table_name}.{column_name} -> {target_table}.{target_column}"\n')
    f.write('    return None\n\n\n')
    f.write('def compute_relationship_strength(table_name: str, column_name: str, has_relationship: bool) -> float:\n')
    f.write('    """Compute relationship evidence strength."""\n')
    f.write('    if has_relationship:\n')
    f.write('        return 0.9\n')
    f.write('    if column_name.endswith("_id"):\n')
    f.write('        return 0.5\n')
    f.write('    return 0.4\n')
print("Created: relationships.py")

# cots_patterns.py
with open(os.path.join(SRC_DIR, "cots_patterns.py"), "w", encoding="utf-8") as f:
    f.write('"""Authorized structured COTS pattern matching (Phase 2 deterministic only)."""\n\n')
    f.write('def match_cots_pattern(table_name: str, column_name: str, value_hint=None) -> dict:\n')
    f.write('    """Match against authorized COTS patterns.\n')
    f.write('    Returns dict with match_strength, product, module, version, or NOT_AVAILABLE.\n')
    f.write('    """\n')
    f.write('    return {\n')
    f.write('        "match_strength": None,\n')
    f.write('        "availability": "NOT_AVAILABLE",\n')
    f.write('        "product": None,\n')
    f.write('        "module": None,\n')
    f.write('        "version": None,\n')
    f.write('        "reason": "COTS pattern matching deferred to Phase 3; no knowledge packs loaded"\n')
    f.write('    }\n')
print("Created: cots_patterns.py")

# confidence.py
with open(os.path.join(SRC_DIR, "confidence.py"), "w", encoding="utf-8") as f:
    f.write('"""Governed confidence calculation from weighted components."""\n')
    f.write('from dataclasses import dataclass\n\n')
    f.write('FORMULA_VERSION = "1.0.0"\n')
    f.write('WEIGHTS = {"naming_strength": 0.35, "type_strength": 0.20, "relationship_strength": 0.25, "cots_match_strength": 0.10, "standard_consistency": 0.10}\n')
    f.write('EVIDENCE_COVERAGE_FLOOR = 0.60\n\n\n')
    f.write('@dataclass\n')
    f.write('class ConfidenceResult:\n')
    f.write('    score: float\n')
    f.write('    components: dict\n')
    f.write('    evidence_coverage: float\n')
    f.write('    formula_version: str\n')
    f.write('    confidence_reason: str\n')
    f.write('    raw_weighted_sum: float\n')
    f.write('    normalized_score: float\n\n\n')
    f.write('def compute_confidence(naming_strength, type_strength, relationship_strength, cots_match_strength=None, standard_consistency=None):\n')
    f.write('    """Compute governed confidence score from components."""\n')
    f.write('    components = {\n')
    f.write('        "naming_strength": {"value": naming_strength, "availability": "AVAILABLE", "weight": WEIGHTS["naming_strength"]},\n')
    f.write('        "type_strength": {"value": type_strength, "availability": "AVAILABLE", "weight": WEIGHTS["type_strength"]},\n')
    f.write('        "relationship_strength": {"value": relationship_strength, "availability": "AVAILABLE", "weight": WEIGHTS["relationship_strength"]},\n')
    f.write('    }\n')
    f.write('    if cots_match_strength is not None:\n')
    f.write('        components["cots_match_strength"] = {"value": cots_match_strength, "availability": "AVAILABLE", "weight": WEIGHTS["cots_match_strength"]}\n')
    f.write('    else:\n')
    f.write('        components["cots_match_strength"] = {"value": None, "availability": "NOT_AVAILABLE", "weight": WEIGHTS["cots_match_strength"]}\n')
    f.write('    if standard_consistency is not None:\n')
    f.write('        components["standard_consistency"] = {"value": standard_consistency, "availability": "AVAILABLE", "weight": WEIGHTS["standard_consistency"]}\n')
    f.write('    else:\n')
    f.write('        components["standard_consistency"] = {"value": None, "availability": "NOT_AVAILABLE", "weight": WEIGHTS["standard_consistency"]}\n')
    f.write('    raw_weighted_sum = 0.0\n')
    f.write('    available_weight = 0.0\n')
    f.write('    total_weight = sum(WEIGHTS.values())\n')
    f.write('    for comp in components.values():\n')
    f.write('        if comp["availability"] == "AVAILABLE" and comp["value"] is not None:\n')
    f.write('            raw_weighted_sum += comp["value"] * comp["weight"]\n')
    f.write('            available_weight += comp["weight"]\n')
    f.write('    evidence_coverage = available_weight / total_weight if total_weight > 0 else 0.0\n')
    f.write('    normalized_score = raw_weighted_sum / available_weight if available_weight > 0 else 0.0\n')
    f.write('    score = round(normalized_score, 4)\n')
    f.write('    if evidence_coverage < EVIDENCE_COVERAGE_FLOOR:\n')
    f.write('        reason = f"Evidence coverage {evidence_coverage:.2f} below floor {EVIDENCE_COVERAGE_FLOOR}; forced review"\n')
    f.write('    else:\n')
    f.write('        avail = len([c for c in components.values() if c["availability"] == "AVAILABLE"])\n')
    f.write('        reason = f"Computed from {avail} available components"\n')
    f.write('    return ConfidenceResult(score=score, components=components, evidence_coverage=round(evidence_coverage, 4), formula_version=FORMULA_VERSION, confidence_reason=reason, raw_weighted_sum=round(raw_weighted_sum, 4), normalized_score=round(normalized_score, 4))\n')
print("Created: confidence.py")

# routing.py
with open(os.path.join(SRC_DIR, "routing.py"), "w", encoding="utf-8") as f:
    f.write('"""Review routing logic for recommendations."""\n\n')
    f.write('LOW_CONFIDENCE_THRESHOLD = 0.75\n\n\n')
    f.write('def route_review(confidence_score, evidence_coverage, privacy_class, relationship_evidence, ontology_concept_id, key_role, contradictions, evidence_coverage_floor=0.60):\n')
    f.write('    """Determine if a recommendation needs review and who should review it."""\n')
    f.write('    review_reason = None\n')
    f.write('    reviewer = None\n')
    f.write('    if privacy_class != "INTERNAL":\n')
    f.write('        review_reason = "Privacy classification requires review"\n')
    f.write('        reviewer = "PRIVACY_STEWARD"\n')
    f.write('    elif relationship_evidence is not None:\n')
    f.write('        review_reason = "Inferred relationship requires confirmation"\n')
    f.write('        reviewer = "DATA_ARCHITECT"\n')
    f.write('    elif ontology_concept_id is None:\n')
    f.write('        review_reason = "No approved ontology concept mapped"\n')
    f.write('        reviewer = "DOMAIN_STEWARD"\n')
    f.write('    elif contradictions is not None:\n')
    f.write('        review_reason = "Conflicting evidence requires resolution"\n')
    f.write('        reviewer = "DOMAIN_STEWARD"\n')
    f.write('    elif evidence_coverage < evidence_coverage_floor:\n')
    f.write('        review_reason = f"Evidence coverage {evidence_coverage:.2f} below floor {evidence_coverage_floor}"\n')
    f.write('        reviewer = "DOMAIN_STEWARD"\n')
    f.write('    elif confidence_score < LOW_CONFIDENCE_THRESHOLD:\n')
    f.write('        review_reason = "Confidence below configured threshold"\n')
    f.write('        reviewer = "DOMAIN_STEWARD"\n')
    f.write('    if review_reason is None:\n')
    f.write('        return {"review_reason": None, "recommended_reviewer_role": None}\n')
    f.write('    return {"review_reason": review_reason, "recommended_reviewer_role": reviewer}\n')
print("Created: routing.py")

print("\nAll source intelligence modules created.")
